apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-68tp
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0018-tenant/tkrw-pr712-0075-0018-app/devfile-sample-68tp@sha256:52efff666ff5e5d37db5bf349485763fbe528ee88c1252559c9525d3d6931a65
        name: my-nodejs
        resources: {}
status: {}
